/*
const vec4 colortex1ClearColor    = vec4(0.0, 1.0, 0.0, 1.0); // Normal texture clear value. 
const float ambientOcclusionLevel = 1.0;                      // Vanilla ambient occlusion, blended in device sRGB. 
const float sunPathRotation       = 33.75;
const int depthtex0Format         = RGBA32F;
const int depthtex1Format         = RGBA32F;
const int depthtex2Format         = RGBA32F;
const int colortex0Format         = RGBA32F;                  // Main color. 
const int colortex1Format         = RGBA32F;                  // Normal texture. 
const int colortex2Format         = RGBA32F;                  // Temporary texture used for SMAA edge detection and blending weight calculation. 
const int colortex3Format         = RGBA32F;                  // Previous color texture for TAA. 
const int colortex4Format         = RGBA32F;                  
const int colortex5Format         = RGBA32F;
const int colortex6Format         = RGBA32F;                  // Anti-aliased depth texture, used for depth-sorting velocity in TAA. 
const int colortex7Format         = RGBA32F;                  // Previous TAA texture, used for disocclusion checks. 
const int colortex8Format         = RGBA32F;                  // Matrices from frame N-2. 
const int colortex9Format         = RGBA32F;                  // Previous x2 TAA color texture. 
const int colortex10Format        = RGBA32F;                  // Previous x2 TAA texture. 
const int colortex11Format        = RGBA32F; //r1
const int colortex12Format        = RGBA32F; //r2
const int colortex13Format        = RGBA32F; //r3
const int colortex14Format        = RGBA32F;                  // Pre-computed SMAA area texture. 
const int colortex15Format        = RGBA32F;                  // Pre-computed SMAA search texture. 
const bool colortex3Clear         = false;                    // Previous color texture is non-clearing for TAA blending. 
const bool colortex7Clear         = false;                    // Previous TAA texture is non-clearing for TAA disocclusion checks. 
const bool colortex8Clear         = false;                    // Frame N-2 matrices is non-clearing. 
const bool colortex9Clear         = false;                    // Frame N-2 is non-clearing. 
const bool colortex10Clear        = false;                    // Frame N-2 TAA texture is non-clearing. 
const bool colortex11Clear        = false;
const bool colortex12Clear        = false;
const bool colortex13Clear        = false;
*/